import { CustomerMovieOutputDto, CustomerNewsOfferOutputDto } from "./models/output.model";

export const NOW_SHOWING_MOVIES: CustomerMovieOutputDto[] = [
    {
        id: "1",
        title: "Stray Kids: dominATE",
        image: "/images/movie-current-banners/470x700-straykids.jpg",
        tags: [{ text: "T13", className: "bg-primary text-white" }],
        description: "Stray Kids mang den trai nghiem am nhac dinh cao tren man anh rong.",
        genre: "Am nhac • 06.03.2026",
        trailerYoutubeId: "zSWdZVtXT7E",
    },
    {
        id: "2",
        title: "Khong Con Chung Ta",
        image: "/images/movie-current-banners/470x700-us.jpg",
        tags: [{ text: "T18", className: "bg-primary text-white" }],
        description: "Sau nay chung ta se co tat ca, nhung khong con chung ta.",
        genre: "Tinh cam, Tam ly • 06.03.2026",
        trailerYoutubeId: "8ugaeA-nMTc",
    },
    {
        id: "3",
        title: "Khung Long Don Tet",
        image: "/images/movie-current-banners/470wx700h-jungle.jpg",
        tags: [{ text: "P", className: "bg-green-600 text-white" }],
        description: "Chuyen du lich rung xanh ly ky nhat danh cho ca nha ta.",
        genre: "Hoat hinh • 26.02.2026",
        trailerYoutubeId: "dQw4w9WgXcQ",
    },
    {
        id: "4",
        title: "Quoc Bao",
        image: "/images/movie-current-banners/kokuho_470x700.jpg",
        tags: [{ text: "T13", className: "bg-primary text-white" }],
        description: "Cau chuyen ve di san van hoa va niem tu hao dan toc.",
        genre: "Tam ly, Lich su • 06.03.2026",
        trailerYoutubeId: "5PSNL1qE6VY",
    },
    {
        id: "5",
        title: "Thanh Guoc Diet Quy: Vo Han Thanh",
        image: "/images/movie-current-banners/dsic_theatricalposters_kv_us_ca_vie_1080x1600.jpg",
        tags: [
            { text: "T13", className: "bg-primary text-white" },
            { text: "IMAX", className: "bg-yellow-500 text-slate-900" },
        ],
        description: "Khai hoa tran chien cuoi cung.",
        genre: "Hoat hinh, Hanh dong • 20.02.2026",
        trailerYoutubeId: "fJ9rUzIMcZQ",
    },
    {
        id: "6",
        title: "Nha Ba Toi Mot Phong",
        image: "/images/movie-current-banners/nh_ba_t_i_m_t_ph_ng_poster_-_kc_m_ng_1_t_t_2026.jpg",
        tags: [{ text: "T13", className: "bg-primary text-white" }],
        description: "Cau chuyen gia dinh am ap ngay Tet.",
        genre: "Gia dinh, Hai • Mung 1 Tet 2026",
        trailerYoutubeId: "JGwWNGJdvx8",
    },
    {
        id: "7",
        title: "Cam On Nguoi Da Thuc Cung Toi",
        image: "/images/movie-current-banners/main_condtct_cinema_low.jpg",
        tags: [{ text: "T18", className: "bg-primary text-white" }],
        description: "Danh tang tinh than, tinh yeu va tinh ban.",
        genre: "Tam ly, Tinh cam • 27.02.2026",
        trailerYoutubeId: "hT_nvWreIhg",
    },
    {
        id: "8",
        title: "Nha Minh Di Thoi",
        image: "/images/movie-current-banners/nh_m_nh_i_th_i_poster_cgv.jpg",
        tags: [{ text: "P", className: "bg-green-600 text-white" }],
        description: "Hanh trinh vui nhon cua ca gia dinh.",
        genre: "Gia dinh, Hai • 26.02.2026",
        trailerYoutubeId: "RgKAFK5djSk",
    },
    {
        id: "9",
        title: "Biet Doi Thu Cung: Cuoc Chien Tren Duong Ray",
        image: "/images/movie-current-banners/pets_on_a_train_tet_themed_poster.jpg",
        tags: [{ text: "P", className: "bg-green-600 text-white" }],
        description: "Du xuan cung cau meo — nao nhiet Tet dinh ngo.",
        genre: "Hoat hinh, Phieu luu • Mung 4 Tet 2026",
        trailerYoutubeId: "OPf0YbXqDm0",
    },
    {
        id: "10",
        title: "Doi Gio Hu",
        image: "/images/movie-current-banners/poster_payoff_doi_gio_hu_6.jpg",
        tags: [{ text: "T18", className: "bg-primary text-white" }],
        description: "Chuyen tinh bat hu tu tieu thuyet kinh dien.",
        genre: "Tinh cam, Co dien • 27.02.2026",
        trailerYoutubeId: "kXYiU_JCYtU",
    },
];

export const COMING_SOON_MOVIES: CustomerMovieOutputDto[] = [
    {
        id: "101",
        title: "Jungle Expedition",
        image: "/images/movie-current-banners/470wx700h-jungle.jpg",
        tags: [{ text: "T16", className: "bg-yellow-500 text-black" }],
        description: "Doi cuu ho doi mat khu rung nguy hiem nhat hanh tinh.",
        genre: "Adventure, Action • 18.04.2026",
        trailerYoutubeId: "2Vv-BfVoq4g",
    },
    {
        id: "102",
        title: "Bao Ve Thanh Chu 3",
        image: "/images/movie-current-banners/470wx700h-bvtc_3.jpg",
        tags: [{ text: "T13", className: "bg-orange-400 text-black" }],
        description: "Biet doi quen thuoc tro lai cho tran chien cuoi.",
        genre: "Action, Comedy • 25.04.2026",
        trailerYoutubeId: "09R8_2nJtjg",
    },
    {
        id: "103",
        title: "Janur",
        image: "/images/movie-current-banners/350x495-janur.jpg",
        tags: [{ text: "T18", className: "bg-red-600 text-white" }],
        description: "Loi nguyen co xua tro lai khi gia dinh chuyen nha.",
        genre: "Horror, Thriller • 06.06.2026",
        trailerYoutubeId: "CevxZvSJLk8",
    },
    {
        id: "104",
        title: "Mikura",
        image: "/images/movie-current-banners/350x495-mikura.jpg",
        tags: [{ text: "T16", className: "bg-yellow-500 text-black" }],
        description: "Trong tuong lai dut gay, mot chien binh giu chia khoa hoa giai.",
        genre: "Action, Sci-Fi • 20.06.2026",
        trailerYoutubeId: "fRh_vgS2dFE",
    },
    {
        id: "105",
        title: "Mui Pho",
        image: "/images/movie-current-banners/350x495-muipho.jpg",
        tags: [{ text: "T13", className: "bg-orange-400 text-black" }],
        description: "Hanh trinh tim lai huong vi que nha giua pho thi.",
        genre: "Drama • 28.06.2026",
        trailerYoutubeId: "kJQP7kiw5Fk",
    },
];

export const NEWS_OFFERS_SOURCE: CustomerNewsOfferOutputDto[] = [
    {
        id: "901",
        slug: "summer-combo-week",
        title: "Summer Combo Week",
        dateLabel: "15 Apr 2026",
        publishedAt: "2026-04-15T08:00:00.000Z",
        banner: "/images/banners/980x448_132.png",
        excerpt: "Enjoy discounted popcorn and drinks with selected movie tickets this week.",
        details: [
            "Get up to 30% off selected combo packages during Summer Combo Week.",
            "The promotion applies to eligible theaters and showtimes listed in the app.",
            "Limited quantity offers are available daily until stock runs out.",
        ],
    },
    {
        id: "902",
        slug: "family-day-special",
        title: "Family Day Special",
        dateLabel: "20 Apr 2026",
        publishedAt: "2026-04-20T08:00:00.000Z",
        banner: "/images/banners/980x448-kitkat_1.png",
        excerpt: "Special family bundles and kid-friendly screenings every weekend.",
        details: [
            "Family Day offers include discounted group tickets for selected sessions.",
            "Customers can combine ticket bundles with concession promotions where available.",
            "See theater-specific terms in the booking flow before checkout.",
        ],
    },
    {
        id: "903",
        slug: "member-point-boost",
        title: "Member Point Boost",
        dateLabel: "24 Apr 2026",
        publishedAt: "2026-04-24T08:00:00.000Z",
        banner: "/images/banners/980_x_448_1__3.jpg",
        excerpt: "Earn extra loyalty points when booking through your LTC account.",
        details: [
            "LTC members receive point multipliers on qualifying transactions.",
            "Bonus points are credited automatically after successful ticket confirmation.",
            "Promotion validity and cap limits are shown in your account dashboard.",
        ],
    },
    {
        id: "904",
        slug: "holiday-voucher-drop",
        title: "Holiday Voucher Drop",
        dateLabel: "30 Apr 2026",
        publishedAt: "2026-04-30T08:00:00.000Z",
        banner: "/images/banners/pnj_980x448_1.jpg",
        excerpt: "Claim limited vouchers and apply them to upcoming blockbuster releases.",
        details: [
            "Voucher availability is limited and distributed on a first-come, first-served basis.",
            "Each voucher can only be applied under its assigned campaign terms.",
            "Check expiration dates carefully before confirming your booking.",
        ],
    },
    {
        id: "905",
        slug: "cinema-weekend-deal",
        title: "Cinema Weekend Deal",
        dateLabel: "03 May 2026",
        publishedAt: "2026-05-03T08:00:00.000Z",
        banner: "/images/banners/980wx448h_16__3.jpg",
        excerpt: "Save more on weekend evening screenings.",
        details: [
            "Apply selected weekend offers directly at checkout.",
            "This promotion is available only for eligible sessions.",
            "Please review campaign terms before payment.",
        ],
    },
    {
        id: "906",
        slug: "kids-day-bundle",
        title: "Kids Day Bundle",
        dateLabel: "10 May 2026",
        publishedAt: "2026-05-10T08:00:00.000Z",
        banner: "/images/banners/b_n_sao_c_a_980x448_1__1.png",
        excerpt: "Family-friendly combos for kid-focused screenings.",
        details: [
            "Bundle pricing is available for selected family sessions.",
            "Offers vary by theater and campaign period.",
            "Please check details in your booking flow.",
        ],
    },
    {
        id: "907",
        slug: "lunar-new-year-voucher",
        title: "Lunar New Year Voucher",
        dateLabel: "15 May 2026",
        publishedAt: "2026-05-15T08:00:00.000Z",
        banner: "/images/banners/lny_980_x_448_1.jpg",
        excerpt: "Limited New Year vouchers for premium movie sessions.",
        details: [
            "Voucher stock is limited and distributed by campaign rules.",
            "Each voucher has specific scope and expiration terms.",
            "You can review usage details in your account.",
        ],
    },
];
