name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authKey: ${{ secrets.TS_AUTHKEY }}

      - name: Setup SSH key
        shell: bash
        run: |
          set -e
          echo "Creating SSH directory"
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_25519
          ssh-key-scan -H 100.109.240.84 >> ~/.ssh/known_hosts
          ls -ls ~./ssh

      - name: SSH Deploy
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
        
          ssh -o StrictHostKeyChecking=no dranov@100.109.240.84 << 'EOF'
            cd /home/dranov/Desktop/ltt-ltc/FE/ltt-ltc-web-app
            git pull origin main --no-rebase
            cd ../
            cd ../
            docker conpose up --build -d ltt-ltc-web-app
          EOF